cupom:
  db:
    ip: 127.0.0.1
    porta: 3306
    database: fiscaliza
    usuario: root
<<<<<<< Updated upstream
    senha: 
=======
    senha: 123456
>>>>>>> Stashed changes
spring.main.allow-bean-definition-overriding: true
        
spring:
  datasource:
    url: jdbc:mysql://${cupom.db.ip}:${cupom.db.porta}/${cupom.db.database}?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=UTC
    username: ${cupom.db.usuario}
    password: ${cupom.db.senha}
    database: ${cupom.db.database}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idleTimeout: 120000
      maximumPoolSize: 10
      minimumIdle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        
app:
  version: #project.version#
server:
  servlet:
    context-path: /fiscalizacao-api
  port: 9090
---
cupom:
  db:
    ip: 127.0.0.1
    porta: 3306
    database: fiscaliza
    usuario: root
    senha: 123456
spring.main.allow-bean-definition-overriding: true

     
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://${cupom.db.ip}:${cupom.db.porta}/${cupom.db.database}?createDatabaseIfNotExist=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=UTC
    username: ${cupom.db.usuario}
    password: ${cupom.db.senha}
    database: ${cupom.db.database}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idleTimeout: 120000
      maximumPoolSize: 10
      minimumIdle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    
app:
  version: #project.version#
server:
  servlet:
    context-path: /fiscalizacao-api
  port: 9091

  
  
  