CREATE TABLE ruas(
id INT AUTO_INCREMENT NOT NULL,
bairroID INT NOT NULL,
tipoLogradouro VARCHAR(10) NOT NULL,
nome VARCHAR(40) NOT NULL,
cep VARCHAR(12) NOT NULL,
PRIMARY KEY(id),
CONSTRAINT fk_bairro_rua FOREIGN KEY (bairroID) REFERENCES bairros(id)
)ENGINE=INNODB;