CREATE TABLE bairros(
 id INT AUTO_INCREMENT NOT NULL,
 cidadeID INT NOT NULL,
 nome VARCHAR(70) NOT NULL,
 setor INT NOT NULL,
 PRIMARY KEY(id),
 CONSTRAINT fk_cidade_bairro FOREIGN KEY(cidadeID) REFERENCES cidades(id)
)ENGINE=INNODB;
