CREATE TABLE IF NOT EXISTS notifica(
id INT  PRIMARY KEY AUTO_INCREMENT,
data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
departamento_id  INT NOT NULL,
tiponotificacao_id INT NOT NULL,
imovel_id INT NOT NULL,
usuario_id INT NOT NULL,
multa DECIMAL(10,2),
servico DECIMAL(10,2),
total DECIMAL(10,2),
vencimento date,
status CHAR(1) NOT NULL DEFAULT 'N',
nome_notificado VARCHAR(40),
cpf_notificado VARCHAR(20),
assinou CHAR(1) NOT NULL DEFAULT 'S',
foto_notificacao VARCHAR(255),
cancelado CHAR(1) DEFAULT 'N',
quem_cancelou  INT,
motivo_cancelamento VARCHAR(255),
CONSTRAINT fk_departamento_notifica FOREIGN KEY (departamento_id) REFERENCES departamento(id),
CONSTRAINT fk_tiponotificacao_notifica FOREIGN KEY (tiponotificacao_id) REFERENCES tipo_notificacao(id),
CONSTRAINT fk_imovel_notifica FOREIGN KEY (imovel_id) REFERENCES imovel(id),
CONSTRAINT fk_usuario_notifica FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);
