CREATE TABLE IF NOT EXISTS imovel (
    id INT AUTO_INCREMENT,
    matricula VARCHAR(15),
    contribuinte_id int NOT NULL,
    endereco_id INT  NOT NULL,
    setor INT NOT NULL,
    quadra INT NOT NULL,
    lote VARCHAR(8) NOT NULL,
    unidade INT,
    valor_venal_edificacao DECIMAL(8,2),
    valor_venal_terreno DECIMAL(8,2),
    valor_venal_excedente DECIMAL(8,2),
    valor_venal_imovel DECIMAL(8,2),
    fracao_ideal int,
    total_area_edificada DECIMAL(8,2),
    espaco_reservado DECIMAL(8,2),
    area_terreno DECIMAL(8,2),
    testada_terreno DECIMAL(8,2),
    testada_taxa DECIMAL(8,2),
    profundidade DECIMAL(8,2),
    lado_esquerdo DECIMAL(8,2),
    lado_direito DECIMAL(8,2),
    zoneamento VARCHAR(20),
    PRIMARY KEY(id),
    CONSTRAINT fk_contribuinte_imovel FOREIGN KEY (contribuinte_id) REFERENCES contribuinte(id),
    CONSTRAINT fk_endereco_imovel FOREIGN KEY (endereco_id) REFERENCES endereco(id)
)  ENGINE=INNODB;
